### ISSUE TITLE
As a user, I want to create a user account with my chosen credentials so that I can use services that are exclusively available to registered users

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#1]
### Acceptance Criteria

• The user should be able to register an account by providing a unique username and password.
• Upon successful registration, the user receives a start credit of 50 credits.
• The user should be able to log in using the username and password created during registration.
• The user should be able to log out.
• The login process should validate the credentials and provide error messages for incorrect inputs.
• Upon successful login, the user should be redirected to their home page.

## Development tasks
- [x] sopra-fs24-group-19/c#8
- [x] sopra-fs24-group-19/s#23
- [x] sopra-fs24-group-19/c#9
- [x] sopra-fs24-group-19/s#25
