### ISSUE TITLE
OPTIONAL: As a logged-in user, I should be able to navigate through the ’Home’ page, ’My Profile’ page and ’Jobs’ page

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#15]
Acceptance Criteria:
• Upon logging in, the user should be navigated to the ”Home” page that displays relevant information and options for the user to interact with.
• Users should be able to access the ’Home’, ’Jobs’ and ’My Profile’ pages from the navigation menu.
• Clicking on the ’My Profile’ link or button in the navigation menu should navigate the user to their profile page, where they can view and edit their personal information.
• Clicking on the ’Jobs’ link or button should direct the user to the ’Jobs’ page, where they can view posted jobs, apply for jobs, or view and perform actions on currently ongoing jobs.

- [x] sopra-fs24-group-19/c#9
- [x] sopra-fs24-group-19/s#41
- [x] sopra-fs24-group-19/s#44
