### ISSUE TITLE
As a help seeker I want to select a user from a list of candidates so that I can find the most suitable helper for my needs

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#5]
Acceptance Criteria:
• In the ”my jobs” section, the user can view the requests they posted.
• By selecting ”candidates” on a specific job posting, the users can view the list of candidates who offered their help for the task.
• In the candidates’ overview, the user sees an overview about each candidate, in- cluding name, description and rating.
• By selecting the profile icon on a candidate section, the user gets redirected to the profile view of the candidate they want to inspect.
• By clicking on the ”select” button, the user can select a candidate for the task.
• Upon selecting a candidate, the job status in the candidate’s ”my jobs” section changes to ”accepted”.
• Upon selecting a candidate, the job disappears from all user’s feeds.
• Upon selecting a candidate, the job disappears from all candidate’s ”my jobs” sec- tion, except for the candidate that was selected for the job.

## Development tasks
- [x] sopra-fs24-group-19/c#5
- [x] sopra-fs24-group-19/c#6
- [x] sopra-fs24-group-19/s#32
- [x] sopra-fs24-group-19/s#33

**Comment by sinakle** [comment]
Add option to delete tasks, if no helper is found or if help seeker changes his mind, the help seeker should get back his coins in such a case
