### ISSUE TITLE
As a user, I want to see a leaderboard with all people in the app together with the number of times they helped and their average rating

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#63]
Acceptance Criteria:
• @dana-jpg pls add acceptance criteria

## Development tasks
- [x] sopra-fs24-group-19/client-group19/issues/24
- [x] sopra-fs24-group-19/client-group19/issues/25
- [x] sopra-fs24-group-19/server-group19/issues/71
