### ISSUE TITLE
As a user, once I have marked a recurring job as completed, I want to be automat- ically redirected to a feedback form where I can rate the other person in real-time. In this way, I am ensuring that each party is held accountable and contributions are recognized within the community

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#7]
Acceptance Criteria:
• Immediately after the user has clicked ’Job Done’ button for a task, he should be automatically redirected to a feedback page.
• On the feedback page, users should be able to provide a rating (1-5) and leave a comment about their experience with the other party involved in the task.

- [x] sopra-fs24-group-19/s#69
- [x] sopra-fs24-group-19/s#67
- [ ] sopra-fs24-group-19/c#35
- [ ] sopra-fs24-group-19/c#16
- [x] sopra-fs24-group-19/client-group19#52

**Comment by sinakle** [comment]
Current ToDo's include the enabling of desynced feedback processes for helper and task creator, the submission of feedback should not depend on if the other party has marked the task as done, instead once one party marks the task as done, the TODO list should be closed for the other party so that no new todos can be added
