### ISSUE TITLE
As a user I want to set my address and my tasks address to an actual real address

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/server-group19#74]
Acceptance Criteria:
• The user must be able to select his address from a list of real addresses
• The address will need to have latitude and longitude in order to compute distances
• The user should not be able to adjust the address after selecting a valid address to avoid misalignments
-> We are using the external API Geoapify to provide real addresses to the user

## Development tasks
- [x] sopra-fs24-group-19/c#11
- [x] sopra-fs24-group-19/c#12
- [x] sopra-fs24-group-19/c#13
- [x] sopra-fs24-group-19/c#14
