### ISSUE TITLE
As a help seeker or task creator, once I have marked a recurring job as completed, I want to review the other user so that I can enhance transparency and help other community members to assess which users are trustworthy

### ISSUE THREAD

**Issue by dana-jpg** [sopra-fs24-group-19/server-group19#87]
Acceptance Criteria:}

 - Immediately after the user has clicked 'Job Done' button for a task, he should be automatically redirected to a feedback page.
 - On the feedback page, users should be able to provide a rating (1-5) and leave a comment about their experience with the other party involved in the task.
 -  If a user leaves the feedback page without leaving a review, they should be still able to leave a review by clicking on a "leave review" button in the My Tasks or My Applications section, respectively

- [x] sopra-fs24-group-19/c#40
- [x] sopra-fs24-group-19/s#86
- [x] sopra-fs24-group-19/s#70
- [x] sopra-fs24-group-19/s#69
- [x] sopra-fs24-group-19/s#32
